### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rodney528** [EliteMasterEric/json2object-dynamic#1]
Does this work? Cause if it does I would love to use it.

**Comment by EliteMasterEric** [comment]
This repository was a test bench used to reproduce a bug.

It has since been resolved: https://github.com/FunkinCrew/json2object

**Comment by rodney528** [comment]
oh so funkins can do dynamic without yelling at me?

**Comment by rodney528** [comment]
![image](https://github.com/user-attachments/assets/6b4f5bdc-1d49-4719-9339-9aadd27b7cd5)

didn't work
